name: Deploy DevConnect

on:
  push:
    branches:
      - main

  repository_dispatch:
    types:
      - frontend-updated
      - backend-updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/DevConnect

            echo "Pulling latest code..."

            cd DevConnectBackend
            git pull origin main

            cd ../DevConnectFrontend
            git pull origin main

            cd ../DevConnectInfra
            git pull origin main

            echo "Rebuilding containers..."

            docker compose -f docker-compose.prod.yml build

            echo "Restarting containers..."

            docker compose -f docker-compose.prod.yml up -d

            echo "Deployment complete!"

            docker image prune -f

            echo "Old docker image pruned"

            echo "Deployment complete!"
